sw = 'on'
while sw == 'on':
    print("Contact Information")
    name = input("Name: ")
    address = input("Address: ")
    date = input("Date: ")
    homephone = input("Home #: ")
    altphone = input("Alternate Phone: ")
    print("Beef")
    regular = input("Regular in LB:")
    lean = input("Lean in LB:")
    extralean = input("Extra-Lean 10 cents extra per LB:")
    patties = input("Patties 30 cents extra a lb/ 25lb minimum:")

    #steaks
    print("Steaks")
    ribribeye = input("rib or rib eye")
    ribribeyeamount = input(f"how much rib or rib eye:")
    tbonenewyork = input("T-bone or new york")
    tbonenewyorkamount = input(f"how much T-bone or new york:")
    sirloin = input(f"how much sirloin")
    tenderloin = input(f"how much tenderloin:")
    roundsteak = input(f"how much round:")
    cuberoundsteak = input(f"how much cube round")
    cubesteak = input(f"how much cube steaks:")
    flank = input(f"how much flank:")
    skirt = input(f"how much skirt:")

    #roasts
    print("Roasts")
    roundroast = input(f"how much round:")
    chuckroast = input(f"how much chuck:")

    #other
    print("Other")
    shortribs = input(f"how much short ribs:")
    stewmeat = input(f"how much stew meat:")
    fajitastrips = input(f"how much fajita strips:")
    soupbones = input("how much soup bones:")
    wholeorhalfbrisket = input(f"Whole or half brisket:")
    brisket = input("how much whole or half brisket:")
    primerib = input(f"how much prime rib:")
    otherbeef = input(f"special instructions or requests:")

    #pork
    print("Pork")
    groundorsausage = input(f"do you want it ground or a sausage")
    hotormild = input(f"hot or mild:")
    sausageorgroundamount = input("how much:")
    sidepork = input(f"how much side pork:")
    bacon = input(f"how much bacon:")
    cottagebacon = input(f"how much cottage bacon:")
    ham = input(f"how much ham:")
    hamsteak = input(f"how many ham steaks:")
    steaks = input(f"how many steaks:")
    porkchop = input(f"how many pork chops:")
    shoulderroast = input(f"how much shoulder roast:")
    freshlegroast = input(f"how much fresh leg roast:")
    ribs = input(f"how many ribs:")
    freshorsmoked = input(f"fresh or smoked hocks:")
    hocks = input(f"how many hocks:")
    otherpork = input(f"special instructions or requests:")

    #Lamb
    print("lamb")
    groundorsausageorstewmeat = input(f"do you want ground, sausage, or stew meat:")
    groundorsausageorstewmeatamount = input(f"how much {groundorsausageorstewmeat} do you want:")
    lambchops = input(f"how many lamb chops do you want:")
    lambsteak = input(f"how many lamb steaks do you want:")
    lambroast = input(f"how much lamb roast do you want:")
    legoflamb = input(f"how much leg of lamb do you want:")
    otherlamb = input(f"any special instructions:")
    print(f"Beef")
    print(f"    Ground Beef")
    print(f"    Regular: {regular}")
    print(f"    Lean: {lean}")
    print(f"    Extra-Lean: {extralean}")
    print(f"    Patties: {patties}")
    print(f"    Steaks")
    print(f"    {ribribeye}: {ribribeyeamount}")
    print(f"    {tbonenewyork}: {tbonenewyorkamount}")
    print(f"    Sirloin: {sirloin}")
    print(f"    Tenderloin: {tenderloin}")
    print(f"    Round: {roundsteak}")
    print(f"    Cube Round: {cuberoundsteak}")
    print(f"    Cube Steaks: {cubesteak}")
    print(f"    Flank: {flank}")
    print(f"    Skirt: {skirt}")
    print(f"    Roasts")
    print(f"    Round: {roundroast}")
    print(f"    Chuck: {chuckroast}")
    print(f"    Other")
    print(f"    Short Ribs: {shortribs}")
    print(f"    Stew Meat: {stewmeat}")
    print(f"    Fajita Strips: {fajitastrips}")
    print(f"    Soup Bones: {soupbones}")
    print(f"    {wholeorhalfbrisket} Brisket: {brisket}")
    print(f"    Prime Rib: {primerib}")
    print(f"    Other: {otherbeef}")
    print(f"Pork")
    print(f"    {hotormild} {groundorsausage}: {sausageorgroundamount}")
    print(f"    Side Pork: {sidepork}")
    print(f"    Bacon: {bacon}")
    print(f"    Cottage Bacon: {cottagebacon}")
    print(f"    Ham: {ham}")
    print(f"    Ham Steak: {hamsteak}")
    print(f"    Steaks: {steaks}")
    print(f"    Pork Chops: {porkchop}")
    print(f"    Shoulder Roast: {shoulderroast}")
    print(f"    Fresh Leg Roast: {freshlegroast}")
    print(f"    Ribs: {ribs}")
    print(f"    {freshorsmoked} Hocks: {hocks}")
    print(f"    Other: {otherpork}")
    print(f"Lamb")
    print(f"    {groundorsausageorstewmeat}: {groundorsausageorstewmeatamount}")
    print(f"    Lamb Chops: {lambchops}")
    print(f"    Lamb Steak: {lambsteak}")
    print(f"    Lamb Roast: {lambroast}")
    print(f"    Leg of Lamb: {legoflamb}")
    print(f"    Other: {otherlamb}")
    doublecheck = input("Is this all correct? y/n")
    if doublecheck == "y":
        file = open(f"{name}.txt", "a")
        file.write(f"Contact Information\n")
        file.write(f"Name: {name}\n")
        file.write(f"Address: {address}\n")
        file.write(f"Date: {date}\n")
        file.write(f"Home #: {homephone}\n")
        file.write(f"Alternative Phone: {altphone}\n")
        file.write(f"Beef\n")
        file.write(f"    Ground Beef\n")
        file.write(f"    Regular: {regular}\n")
        file.write(f"    Lean: {lean}\n")
        file.write(f"    Extra-Lean: {extralean}\n")
        file.write(f"    Patties: {patties}\n")
        file.write(f"    Steaks\n")
        file.write(f"    {ribribeye}: {ribribeyeamount}\n")
        file.write(f"    {tbonenewyork}: {tbonenewyorkamount}\n")
        file.write(f"    Sirloin: {sirloin}\n")
        file.write(f"    Tenderloin: {tenderloin}\n")
        file.write(f"    Round: {roundsteak}\n")
        file.write(f"    Cube Round: {cuberoundsteak}\n")
        file.write(f"    Cube Steaks: {cubesteak}\n")
        file.write(f"    Flank: {flank}\n")
        file.write(f"    Skirt: {skirt}\n")
        file.write(f"    Roasts\n")
        file.write(f"    Round: {roundroast}\n")
        file.write(f"    Chuck: {chuckroast}\n")
        file.write(f"    Other\n")
        file.write(f"    Short Ribs: {shortribs}\n")
        file.write(f"    Stew Meat: {stewmeat}\n")
        file.write(f"    Fajita Strips: {fajitastrips}\n")
        file.write(f"    Soup Bones: {soupbones}\n")
        file.write(f"    {wholeorhalfbrisket} Brisket: {brisket}\n")
        file.write(f"    Prime Rib: {primerib}\n")
        file.write(f"    Other: {otherbeef}\n")
        file.write(f"Pork\n")
        file.write(f"    {hotormild} {groundorsausage}: {sausageorgroundamount}\n")
        file.write(f"    Side Pork: {sidepork}\n")
        file.write(f"    Bacon: {bacon}\n")
        file.write(f"    Cottage Bacon: {cottagebacon}\n")
        file.write(f"    Ham: {ham}\n")
        file.write(f"    Ham Steak: {hamsteak}\n")
        file.write(f"    Steaks: {steaks}\n")
        file.write(f"    Pork Chops: {porkchop}\n")
        file.write(f"    Shoulder Roast: {shoulderroast}\n")
        file.write(f"    Fresh Leg Roast: {freshlegroast}\n")
        file.write(f"    Ribs: {ribs}\n")
        file.write(f"    {freshorsmoked} Hocks: {hocks}\n")
        file.write(f"    Other: {otherpork}\n")
        file.write(f"Lamb\n")
        file.write(f"    {groundorsausageorstewmeat}: {groundorsausageorstewmeatamount}\n")
        file.write(f"    Lamb Chops: {lambchops}\n")
        file.write(f"    Lamb Steak: {lambsteak}\n")
        file.write(f"    Lamb Roast: {lambroast}\n")
        file.write(f"    Leg of Lamb: {legoflamb}\n")
        file.write(f"    Other: {otherlamb}\n")
        file.close()
        print("Thank you for ordering and have a great day! \n if you have any questions please call us at 1+777-777-7777")
        sw = 'off'
    elif doublecheck == 'n' or doublecheck == 'no':
        triplecheck = input("Are you sure you messed up your order? y/n")
        if triplecheck == 'y':
            break
        elif triplecheck == 'n':
            file = open(f"{name}.txt", "a")
            file.write(f"Contact Information\n")
            file.write(f"Name: {name}\n")
            file.write(f"Address: {address}\n")
            file.write(f"Date: {date}\n")
            file.write(f"Home #: {homephone}\n")
            file.write(f"Alternative Phone: {altphone}\n")
            file.write(f"Beef\n")
            file.write(f"    Ground Beef\n")
            file.write(f"    Regular: {regular}\n")
            file.write(f"    Lean: {lean}\n")
            file.write(f"    Extra-Lean: {extralean}\n")
            file.write(f"    Patties: {patties}\n")
            file.write(f"    Steaks\n")
            file.write(f"    {ribribeye}: {ribribeyeamount}\n")
            file.write(f"    {tbonenewyork}: {tbonenewyorkamount}\n")
            file.write(f"    Sirloin: {sirloin}\n")
            file.write(f"    Tenderloin: {tenderloin}\n")
            file.write(f"    Round: {roundsteak}\n")
            file.write(f"    Cube Round: {cuberoundsteak}\n")
            file.write(f"    Cube Steaks: {cubesteak}\n")
            file.write(f"    Flank: {flank}\n")
            file.write(f"    Skirt: {skirt}\n")
            file.write(f"    Roasts\n")
            file.write(f"    Round: {roundroast}\n")
            file.write(f"    Chuck: {chuckroast}\n")
            file.write(f"    Other\n")
            file.write(f"    Short Ribs: {shortribs}\n")
            file.write(f"    Stew Meat: {stewmeat}\n")
            file.write(f"    Fajita Strips: {fajitastrips}\n")
            file.write(f"    Soup Bones: {soupbones}\n")
            file.write(f"    {wholeorhalfbrisket} Brisket: {brisket}\n")
            file.write(f"    Prime Rib: {primerib}\n")
            file.write(f"    Other: {otherbeef}\n")
            file.write(f"Pork\n")
            file.write(f"    {hotormild} {groundorsausage}: {sausageorgroundamount}\n")
            file.write(f"    Side Pork: {sidepork}\n")
            file.write(f"    Bacon: {bacon}\n")
            file.write(f"    Cottage Bacon: {cottagebacon}\n")
            file.write(f"    Ham: {ham}\n")
            file.write(f"    Ham Steak: {hamsteak}\n")
            file.write(f"    Steaks: {steaks}\n")
            file.write(f"    Pork Chops: {porkchop}\n")
            file.write(f"    Shoulder Roast: {shoulderroast}\n")
            file.write(f"    Fresh Leg Roast: {freshlegroast}\n")
            file.write(f"    Ribs: {ribs}\n")
            file.write(f"    {freshorsmoked} Hocks: {hocks}\n")
            file.write(f"    Other: {otherpork}\n")
            file.write(f"Lamb\n")
            file.write(f"    {groundorsausageorstewmeat}: {groundorsausageorstewmeatamount}\n")
            file.write(f"    Lamb Chops: {lambchops}\n")
            file.write(f"    Lamb Steak: {lambsteak}\n")
            file.write(f"    Lamb Roast: {lambroast}\n")
            file.write(f"    Leg of Lamb: {legoflamb}\n")
            file.write(f"    Other: {otherlamb}\n")
            file.close()
            print("Thank you for ordering and have a great day! \n if you have any questions please call us at 1+777-777-7777")
            sw = 'off'
